/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Jan 8 2019
 * Processor: PIC18F452
 * Compiler:  MPLAB C18
 */


#include <p18f452.h>

#pragma config WDT = OFF
#pragma config OSCS = OFF
#pragma config OSC = HS

#define Bulb1 PORTDbits.RD0
#define Bulb2 PORTDbits.RD1
#define Bulb3 PORTDbits.RD2
#define Bulb4 PORTDbits.RD3

unsigned char received;
void chk_isr(void);
void RCISR();
void TXISR();
unsigned char receive();
void uartInit();

/*---------------------------------UART INITIALIZATION---------------------------*/
void uartInit()
{
 
    TRISCbits.TRISC6 = 0; // TX Pin set as output
    TRISCbits.TRISC7 = 1; // RX Pin set as input
 
    SPBRG = 15;
    TXSTA = 0x20;  
    RCSTA = 0x90;   

    RCSTAbits.SPEN  = 1;    // Enable serial port pins
    TXSTAbits.TXEN  = 1;    // enable transmission
}

//**Function to send one byte of date to UART**//
void transmit(char byte)  
{
    while(PIR1bits.TXIF == 0);  // hold the program till TX buffer is free
    TXREG = byte; //Load the transmitter buffer with the received value
}

unsigned char receive()   
{
    if(RCSTAbits.OERR) // check for Error 
    {
        RCSTAbits.CREN = 0; //If error -> Reset 
        RCSTAbits.CREN = 1; //If error -> Reset 
    }
    
    while(PIR1bits.RCIF == 0);  // hold the program till RX buffer is free
    
    return RCREG; //receive the value and send it to main function
}

/*---------------------------------UART INITIALIZATION ENDED---------------------------*/

/*---------------------------------INTERRUPT HANDLING---------------------------*/
 void RCISR()
{
		received = receive();
	    if(received == '0')
	    {	
	    	Bulb1 = 0;
	    }

	    if(received == '1')
	    {	
		   	Bulb1 = 1;
	    }

	    if(received == '2')
	   {	
		   	Bulb2 = 0;
	   }

	    if(received == '3')
	    {	
	    	Bulb2 = 1;
	    }

	    if(received == '4')
	    {	
	   	   	Bulb3 = 0;
	    }

	    if(received == '5')
	    {	
		   	Bulb3 = 1;
	    }

	    if(received == '6')
	    {	
	    	Bulb4 = 0;
	    }

	    if(received == '7')
	    {	
	    	Bulb4 = 1;
	    }		
}





#pragma code hPInterrupt = 0x08
void hPInterrupt(void)
{
	_asm
		GOTO chk_isr
	_endasm
}
#pragma code
#pragma interrupt chk_isr
void chk_isr(void)
{
	/*if(PIR1bits.TXIF == 1)
	{
		TXISR();
	}*/
	if(PIR1bits.RCIF == 1)
	{
		RCISR();
	}
}



/*---------------------------------INTERRUPT HANDLING ENDED---------------------------*/


void main()
 {
	TRISD = 0x00;
	uartInit();
	PIE1bits.TXIE = 1;
	PIE1bits.RCIE = 1;
	INTCONbits.PEIE = 1;
	INTCONbits.GIE = 1;
	while(1);
 }